### REPORTE - LISTAR TODOS
GET http://localhost:6015/reportes


### REPORTE - BUSCAR POR ID
GET http://localhost:6015/reportes/1


### REPORTE - CREAR
POST http://localhost:6015/reportes
Content-Type: application/json

{
  "titulo": "Reporte académico",
  "descripcion": "Reporte de desempeño del estudiante",
  "tipo": "ACADEMICO",
  "fecha": "2026-01-18",
  "idUsuario": 1
}


### REPORTE - ACTUALIZAR
PUT http://localhost:6015/reportes/1
Content-Type: application/json

{
  "titulo": "Reporte académico actualizado",
  "descripcion": "Reporte corregido y validado",
  "tipo": "ACADEMICO",
  "fecha": "2026-01-19",
  "idUsuario": 1
}


### REPORTE - ELIMINAR
DELETE http://localhost:6015/reportes/1
