### PROGRESO - LISTAR
GET http://localhost:6017/progreso-estudiantes


### PROGRESO - CREAR
POST http://localhost:6017/progreso-estudiantes
Content-Type: application/json

{
  "idEstudiante": 1,
  "idCurso": 2,
  "porcentajeAvance": 45.5,
  "estado": "EN_PROGRESO"
}


### PROGRESO - BUSCAR POR ID
GET http://localhost:6017/progreso-estudiantes/1


### PROGRESO - ACTUALIZAR
PUT http://localhost:6017/progreso-estudiantes/1
Content-Type: application/json

{
  "idEstudiante": 1,
  "idCurso": 2,
  "porcentajeAvance": 80.0,
  "estado": "COMPLETADO"
}


### PROGRESO - ELIMINAR
DELETE http://localhost:6017/progreso-estudiantes/1
