### LISTAR
GET http://localhost:6014/incidencias

### GUARDAR
POST http://localhost:6014/incidencias
Content-Type: application/json

{
  "titulo": "Error de acceso",
  "descripcion": "No se puede acceder al curso",
  "estado": "ABIERTA",
  "idUsuario": 1
}

### BUSCAR POR ID
GET http://localhost:6014/incidencias/1

### ACTUALIZAR
PUT http://localhost:6014/incidencias/1
Content-Type: application/json

{
  "titulo": "Error de acceso",
  "descripcion": "Error corregido",
  "estado": "CERRADA",
  "idUsuario": 1
}

### ELIMINAR
DELETE http://localhost:6014/incidencias/1
