###### Agregar Pais
POST http://127.0.0.1:6001/paises HTTP/1.1
Content-Type: application/json

{
    "nombrePais": "Peru"
}

###### Obtener todos los Paises
GET http://127.0.0.1:6001/paises HTTP/1.1
Content-Type: application/json


###### Obtener Pais por ID
GET http://127.0.0.1:6001/paises/1 HTTP/1.1
Content-Type: application/json


###### Actualizar Pais
PUT http://127.0.0.1:6001/paises/1 HTTP/1.1
Content-Type: application/json

{
    "nombrePais": "Argentina"
}


###### Eliminar Pais
DELETE http://127.0.0.1:6001/paises/2 HTTP/1.1
Content-Type: application/json
