### INSCRIPCION - LISTAR
GET http://localhost:6018/inscripciones


### INSCRIPCION - CREAR
POST http://localhost:6018/inscripciones
Content-Type: application/json

{
  "idEstudiante": 1,
  "idCurso": 2,
  "fechaInscripcion": "2026-01-18",
  "estado": "ACTIVA"
}


### INSCRIPCION - BUSCAR POR ID
GET http://localhost:6018/inscripciones/1


### INSCRIPCION - ACTUALIZAR
PUT http://localhost:6018/inscripciones/1
Content-Type: application/json

{
  "idEstudiante": 1,
  "idCurso": 2,
  "fechaInscripcion": "2026-01-18",
  "estado": "FINALIZADA"
}


### INSCRIPCION - ELIMINAR
DELETE http://localhost:6018/inscripciones/1
