### ===============================
### LISTAR TODAS LAS CIUDADES
### ===============================
GET http://localhost:6002/ciudades
Accept: application/json


### ===============================
### BUSCAR CIUDAD POR ID
### ===============================
GET http://localhost:6002/ciudades/1
Accept: application/json


### ===============================
### CREAR NUEVA CIUDAD
### ===============================
POST http://localhost:6002/ciudades
Content-Type: application/json

{
  "nombreCiudad": "paine"
}


### ===============================
### ACTUALIZAR CIUDAD
### ===============================
PUT http://localhost:6002/ciudades/1
Content-Type: application/json

{
  "nombreCiudad": "Valparaíso"
}


### ===============================
### ELIMINAR CIUDAD
### ===============================
DELETE http://localhost:6002/ciudades/1
