### ============================
### LISTAR PLATAFORMAS EDUCATIVAS
### ============================
GET http://localhost:6008/plataformas-educativas
Accept: application/json


### ============================
### BUSCAR PLATAFORMA POR ID
### ============================
GET http://localhost:6008/plataformas-educativas/1
Accept: application/json


### ============================
### CREAR PLATAFORMA EDUCATIVA
### ============================
POST http://localhost:6008/plataformas-educativas
Content-Type: application/json

{
  "nombrePlataforma": "Moodleee",
  "descripcion": "Plataforma educativa de código abierto",
  "urlPlataforma": "https://moodle.org"
}


### ============================
### ACTUALIZAR PLATAFORMA EDUCATIVA
### ============================
PUT http://localhost:6008/plataformas-educativas/1
Content-Type: application/json

{
  "nombrePlataforma": "Moodle Actualizada",
  "descripcion": "Plataforma LMS utilizada en educación superior",
  "urlPlataforma": "https://moodle.org"
}


### ============================
### ELIMINAR PLATAFORMA EDUCATIVA
### ============================
DELETE http://localhost:6008/plataformas-educativas/1
Accept: application/json
